// Code generated by templ@v0.2.364 DO NOT EDIT.

package css

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "strings"

func Sidebar() templ.CSSClass {
	var templCSSBuilder strings.Builder
	templCSSBuilder.WriteString(`width:250px;`)
	templCSSBuilder.WriteString(`position:fixed;`)
	templCSSBuilder.WriteString(`top:0;`)
	templCSSBuilder.WriteString(`left:0;`)
	templCSSBuilder.WriteString(`height:100vh; 
    background-color: #f8f9fa;`)
	templCSSBuilder.WriteString(`box-shadow:2px 0 5px rgba(0,0,0,0.1); 
    padding: 20px;`)
	templCSSBuilder.WriteString(`box-sizing:border-box;`)
	templCSSID := templ.CSSID(`Sidebar`, templCSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templCSSID,
		Class: templ.SafeCSS(`.` + templCSSID + `{` + templCSSBuilder.String() + `}`),
	}
}

func AvatarContainer() templ.CSSClass {
	var templCSSBuilder strings.Builder
	templCSSBuilder.WriteString(`position:relative;`)
	templCSSBuilder.WriteString(`width:50px;`)
	templCSSBuilder.WriteString(`height:50px;`)
	templCSSBuilder.WriteString(`border-radius:20%;`)
	templCSSBuilder.WriteString(`overflow:hidden;`)
	templCSSBuilder.WriteString(`border:2px solid #007bff;`)
	templCSSBuilder.WriteString(`box-shadow:0 2px 4px rgba(0, 0, 0, 0.1);`)
	templCSSBuilder.WriteString(`margin-top:20px;`)
	templCSSBuilder.WriteString(`object-fit:cover;`)
	templCSSID := templ.CSSID(`AvatarContainer`, templCSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templCSSID,
		Class: templ.SafeCSS(`.` + templCSSID + `{` + templCSSBuilder.String() + `}`),
	}
}

func AvatarImage() templ.CSSClass {
	var templCSSBuilder strings.Builder
	templCSSBuilder.WriteString(`width:100%; 
    height: 100%;`)
	templCSSBuilder.WriteString(`object-fit:cover;`)
	templCSSID := templ.CSSID(`AvatarImage`, templCSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templCSSID,
		Class: templ.SafeCSS(`.` + templCSSID + `{` + templCSSBuilder.String() + `}`),
	}
}

func SidebarItem() templ.CSSClass {
	var templCSSBuilder strings.Builder
	templCSSBuilder.WriteString(`margin-bottom:30px;`)
	templCSSID := templ.CSSID(`SidebarItem`, templCSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templCSSID,
		Class: templ.SafeCSS(`.` + templCSSID + `{` + templCSSBuilder.String() + `}`),
	}
}
